### ISSUE TITLE
Ini kenapa?

### ISSUE THREAD

**Issue by hctofu86** [mbahArip/next-gdrive-index#10]
Gak tau lagi ini kenapa selalu begitu, dan tutorial deploy juga belum diupdate. Kalau bisa ada tutor bahasa indonesia juga itu sangat membantu.
Btw, terima kasih sudah buat ini repo. akhirnya ada index keren selain gdi.

<img width="960" alt="Screenshot 2024-04-12 011751" src="https://github.com/mbahArip/next-gdrive-index/assets/108676292/fa366aaa-5c35-44b1-9d93-44e0ed14c267">

**Comment by mbahArip** [comment]
Bisa coba dicek error lognya di page deployment vercelnya gan?

Iya gan masih belum sempet update wikinya hehe, mungkin nanti weekend saya update wikinya
Tapi gampangnya sih ikutin yg di wiki, terus ikutin [migration guide](https://github.com/mbahArip/next-gdrive-index?tab=readme-ov-file#migration-guide) doang sih gan

**Comment by mbahArip** [comment]
Problem di environment `ENCRYPTION_KEY`nya gan
errornya gara2 gagal decrypt `rootFolder` itu

bisa ikutin [bagian ini](https://github.com/mbahArip/next-gdrive-index/blob/main/README.md?plain=1#L173)

**Comment by mbahArip** [comment]
Bisa langsung di vercel aja sebenernya.
File `.env` dipake pas dijalanin di lokal aja

**Comment by mbahArip** [comment]
baiknya sih pake encryption key sendiri.
bisa kata2 / random character, yang penting 16 huruf.

kalau misalnya dikosongin juga harusnya ga masalah, nanti bakal pake default bawaan project ini (`next-gdrive-index`)

**Comment by mbahArip** [comment]
Sorry baru nemu freetime.
W lagi bikin deploying guide di webnya include dari bikin google cloud project sampe env + config.

Expect bisa pake deploying guide ini minggu depan / akhir bulan ini. Cheers.
