### ISSUE TITLE
An error occured in the server component render

### ISSUE THREAD

**Issue by SyedTahseen** [mbahArip/next-gdrive-index#14]
An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error?
what is it or if I'm making mistake in deployment?

**Comment by mbahArip** [comment]
I just checked your fork, you need to encrypt the root folder inside config file.

You need to run the project on local first, then encrypt it from `http://localhost:<PORT>/api/internal/encrypt?q=<folder ID>`
This will encrypt the folder ID using your `ENCRYPTION_KEY` inside the `.env` file

**Comment by SyedTahseen** [comment]
I don't know how to run this on local host. if there could be a video guide on it. or you can add this step on your wiki page it would be helpful for new people.
And I kept the encryption key same as your. and you can see folder id too. if you can do this part for me and add it on my fork. it will be much thankful

**Comment by mbahArip** [comment]
If you can't run this on local, you can use this codesandbox to generate the encrypted ID
https://codesandbox.io/p/sandbox/generate-encrypt-hpzsr3

You can fill the Encryption Key with the value from the environment file, and folder ID on the Input.

**Comment by SyedTahseen** [comment]
It worked now. actually i was following the wiki page deployment method but there was nothing like encrypting folder id. kindly add this on wiki page so other people can benefit from it. and thanks for this beautiful index and support ❤️

**Comment by mbahArip** [comment]
Thank you for the feedback

Since I'm still developing the project, and there might be some changes.
And the updated guide for v2 are still on the Readme files.

But I'll update the wiki as soon as I finish the current feature I'm working on.

**Comment by SyedTahseen** [comment]
![Screenshot_20240504-115134](https://github.com/mbahArip/next-gdrive-index/assets/53108646/49a7a737-8b6f-467f-a7d5-d4240272fe56)
- I have updated all variables from vercel and public domain var too as you can see in screenshot. but whenever I'm trying to copy download link. it is copying link from other domains.
- when i try to delete .env file from github fork my deployment failed even tho i have updated var on vercel.
- can we just get direct download link from protected website so anyone can download from that link without password.
- what is this .password thing for directory? is it like if we upload .password file that contains pwd inside will lock that specific directory?
- can you add an option that we can even upload files through site?

**Comment by mbahArip** [comment]
- It should be `NEXT_PUBLIC_DOMAIN` instead of `PUBLIC_DOMAIN`
- Can you provide the error build logs from vercel?
- In the config files on `apiConfig` section, there are options called `allowDownloadProtectedFile`.
If you set it to true, anyone can download the files from private index / protected directory.
(You may want to change the temporary token duration to something high, by default protected file copied will have 6 hours token)
- Yes, it will mark the directory as protected and will ask the user the password before accessing it.
- There are no plan for that yet
- `master_key` are no longer used in version 2.x, it was used to bypass the file / folder password when checking for path.
- We support Shared Drive, but not with shared folder. But multiple drives are on the list of things I want to implement next.

**Comment by SyedTahseen** [comment]
![Screenshot_20240504-154232](https://github.com/mbahArip/next-gdrive-index/assets/53108646/205df03b-cec3-48a2-88a5-6578fe6a91e1)
- I've updated next_public_domain in var but still when i copy download link it is copying through development url.
- This time it didn't show error log
- I have updated allowDownloadProtectedFile to true but still when i try to download through direct download link it shows password protected.
![Screenshot_20240504-153007 (1)](https://github.com/mbahArip/next-gdrive-index/assets/53108646/4481c1dc-a2c0-4118-a5d3-b77f2608f997)
as you can check my fork that i have updated

**Comment by mbahArip** [comment]
My bad, it's the config fault.
You can open the config files, and swap the `basePath` value.
It should be `process.env.NEXT_PUBLIC_DOMAIN || process.env.NEXT_PUBLIC_VERCEL_URL`
![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/4a6a7b6d-3462-4772-b901-bc1f96131efb)

Also my fault, you can try to add [Line 38](https://github.com/mbahArip/next-gdrive-index/blob/8fbf531872b0651de85ec729091f1e1644f6ee44/src/app/api/download/%5BencryptedId%5D/route.ts#L38) in your `/src/app/api/download/[encryptedId]/route.ts`

Is it when exploring the files or downloading? If it's when exploring the files you still need to input the password to the closest protected folder.
e.g. `/Protected 1(pass=123)/Protected 2(pass=234)/file.ext`, you only need to input the password for `Protected 2` folder, which is 234.

**Comment by SyedTahseen** [comment]
Fixed url, and direct download link
I couldn't understand that /password part

I was saying that I have added .password file in a folder and it contains password 123 and nothing else but when I try to access that file it says password isn't set 
![Screenshot_20240504-194835](https://github.com/mbahArip/next-gdrive-index/assets/53108646/4524a377-0cd2-46b4-ae5e-de444340c128) as u can see in screenshot

**Comment by mbahArip** [comment]
Sorry for confusing error message
It means that you haven't set the password on the site itself / the index can't find password cookies for that path

I'll update the message ASAP

**Comment by oTahseen** [comment]
sure I'm waiting

**Comment by SyedTahseen** [comment]
sure im waiting

**Comment by mbahArip** [comment]
The error message when the user doesn't have the password are updated.

**Comment by SyedTahseen** [comment]
i guess it was showing error even the password is correct. did you fix it?

**Comment by mbahArip** [comment]
weird, i haven't met such issues.
can you provide some screenshot?

**Comment by SyedTahseen** [comment]
I have uploaded this file as you can see password inside
![1715138890605](https://github.com/mbahArip/next-gdrive-index/assets/53108646/7f407145-f78c-4e77-8e89-cdf5da9a94cd)
but it is showing error
![1715138902715](https://github.com/mbahArip/next-gdrive-index/assets/53108646/fa9389b3-f839-4c2e-88ca-b5153ca09eec)
later on i will update my fork

**Comment by mbahArip** [comment]
Can you recheck if the password file have like a line break inside? It might be the cause.

Since the `CheckPassword` logic are only fetch the `.password` file inside the path, then match it with the input.

**Comment by SyedTahseen** [comment]
password file is okay. i have checked it many times because i thought im making mistakes

**Comment by mbahArip** [comment]
Let me recheck the whole password checking again.

**Comment by mbahArip** [comment]
I've check everything and tried to replicate it myself, but it's working as intended.
Can you try to generate the config and env from the new [Deployment Guide](https://drive-demo.mbaharip.com/deploy#config) and see if it's fix the problem?

**Comment by SyedTahseen** [comment]
I have re forked and deployed again. and added new config.
![1715265753310](https://github.com/mbahArip/next-gdrive-index/assets/53108646/5418416d-5830-469f-86bf-38839966bf03)
and added .password again. but still same problem. idk if im making mistake or it's code problem. 
I have one question do i have to add extension any extension on .password file? i just made .password file that include password in it nothing else

**Comment by mbahArip** [comment]
It's really weird, can you send me the `.password` file here for me to test?
I've tried everything but can't replicate the issues on my side

You don't need to add extension, the fact it's asking the password means it's recognizing the file.
But somehow in your case it's failed when validating the password

**Comment by SyedTahseen** [comment]
I don't know how but it worked now

**Comment by mbahArip** [comment]
Glad that it's fixed.

Make sure you've set the serverless function region as close as your / your user region in Vercel.
Google Drive API doesn't use path-like query, so the deeper the file, the longer it would load.
Since it checks for each file / folder to make sure the path is correct / exist.

**Comment by SyedTahseen** [comment]
I got it and everything is fixed now thank you so much for your help. keep working like this on project
