### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by tuta-amb** [mbahArip/next-gdrive-index#22]
Hey there, I just want to say this project is really nice and congratulate you on your hard work. I've noticed a problem which is that although it appears the caching has been set to 60 seconds, whenever I make changes in Google Drive it takes up to 30 minutes to reflect on the index, generally it's somewhere around 20 minutes.

This isn't that big of a problem, but it would be much appreciated if this could be increased. Thanks!

**Comment by mbahArip** [comment]
Look's like I'm completely forgot to remove the revalidate on google drive fetch.
So for now it would revalidate every 1 hour instead of 1 minute like the route revalidate.

Pushing the fix now

**Comment by mbahArip** [comment]
Should be fixed by this commit fcdac1f
