### ISSUE TITLE
Add support for folder shortcut

### ISSUE THREAD

**Issue by phuchptty** [mbahArip/next-gdrive-index#28]
Hi, My folder contains many shortcuts from another folders (public). I tried but it can't index shortcut to those folders.

![image](https://github.com/mbahArip/next-gdrive-index/assets/13364457/0cbb204d-ae1f-43a1-b41d-380600553f7d)

**Comment by mbahArip** [comment]
There are no plan to implement shortcut folder / file to the index.

It's pretty tricky to implement it with how the current path transformation work.
Since the shortcut has its own ID, and even if I take the target ID, the target parent ID would not be the same as the shortcut parent ID
