### ISSUE TITLE
Bugged & Laggy

### ISSUE THREAD

**Issue by mioscape** [mbahArip/next-gdrive-index#6]
The content is not rendered in the Phone, and it's too Laggy when scrolling the page.

![Screenshot_20240319-041340_Chrome.png](https://github.com/mbahArip/next-gdrive-index/assets/43681888/b6167ca8-7151-46ea-aec6-18cebdb10df9)

**Comment by mbahArip** [comment]
Thank you for the report, I'll try fix it this weekend.

**Comment by mbahArip** [comment]
Sorry for slow update.
I've updated the project so now it's using `shadcn/ui` to prevent visual bugs and performance drop.
You can check the new demo from the same url

![image](https://github.com/mbahArip/next-gdrive-index/assets/62494292/050da6a5-2262-4f1b-9fd9-2c7b16a578ea)
